# Generated by Django 6.0.3 on 2026-03-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='id',
            new_name='id_seguranca',
        ),
    ]
